### ISSUE TITLE
Introducción y explicación básica

### ISSUE THREAD

**Issue by vcalzadaga** [CIFP-Jose-luis-Garci/ZeikkusAwakening#1]

**Comment by IIlae** [comment]
Dejo un link al archivo de drive en el que estoy haciendo mi parte a parte de subirla para revisar
https://docs.google.com/document/d/1evLsEad0NgRjNcqJ32tOtnzMbC7l6tkURRpkxG-4CuI/edit?usp=sharing

**Comment by IIlae** [comment]
[Introducción y explicación básica.pdf](https://github.com/CIFP-Jose-luis-Garci/ZeikkusAwakening/files/7522818/Introduccion.y.explicacion.basica.pdf)
