### ISSUE TITLE
Requerimientos funcionales y pantallas de ejemplo

### ISSUE THREAD

**Issue by ZeikkuSSJ7** [CIFP-Jose-luis-Garci/ZeikkusAwakening#12]

**Comment by mirirore** [comment]
[Interfaz_Pantallas.pdf](https://github.com/CIFP-Jose-luis-Garci/ZeikkusAwakening/files/7496876/Interfaz_Pantallas.pdf)

Adjunto PDF con Interfaz y ejemplos

**Comment by vcalzadaga** [comment]
Correcto
