### ISSUE TITLE
Core Gameplay y Game Flow

### ISSUE THREAD

**Issue by ZeikkuSSJ7** [CIFP-Jose-luis-Garci/ZeikkusAwakening#15]
- [x] Core gameplay
- [x] Game flow

**Comment by ZeikkuSSJ7** [comment]
[Core Gameplay y Game Flow.pdf](https://github.com/CIFP-Jose-luis-Garci/ZeikkusAwakening/files/7496952/Core.Gameplay.y.Game.Flow.pdf)

Terminado el 5 de Noviembre

**Comment by vcalzadaga** [comment]
Muy bien
