### ISSUE TITLE
Personajes y enemigos

### ISSUE THREAD

**Issue by ZeikkuSSJ7** [CIFP-Jose-luis-Garci/ZeikkusAwakening#16]
- [x] Personajes
- [x] Enemigos

**Comment by ZeikkuSSJ7** [comment]
[Personajes y enemigos.pdf](https://github.com/CIFP-Jose-luis-Garci/ZeikkusAwakening/files/7496962/Personajes.y.enemigos.pdf)

Terminado el 6 de Noviembre

**Comment by vcalzadaga** [comment]
En cuanto a los personajes y enemigos, echo en falta que incluyáis las habilidades de cada uno. Por ejemplo: x personaje corre más rápido que los demás, puede utilizar la espada como arma por defecto, es más habilidoso en el control de la magia....

**Comment by ZeikkuSSJ7** [comment]
Lo explicamos en los elementos de gameplay, este punto es sólo para dar una descripción y trasfondo de cada uno
