### ISSUE TITLE
Físicas de juego e inteligencia artificial

### ISSUE THREAD

**Issue by ZeikkuSSJ7** [CIFP-Jose-luis-Garci/ZeikkusAwakening#18]
- [x] Físicas de juego
- [x] Inteligencia Artificial

**Comment by ZeikkuSSJ7** [comment]
[Fisicas de juego e Inteligencia Artificial.pdf](https://github.com/CIFP-Jose-luis-Garci/ZeikkusAwakening/files/7496976/Fisicas.de.juego.e.Inteligencia.Artificial.pdf)

Terminado el 7 de Noviembre

**Comment by vcalzadaga** [comment]
físicas e IA muy bien definidas
