### ISSUE TITLE
Animaciones personaje

### ISSUE THREAD

**Issue by Guillermo-Manso** [CIFP-Jose-luis-Garci/ZeikkusAwakening#22]
- [x] Pensar animaciones
- [x] Buscar animaciones
- [x] Retocar animaciones
- [x] Exportar animaciones

**Comment by alhgo** [comment]
Creo que es el momento de que alguien, el encargado, lo meta ya en el proyecto de Unity del repositorio y vayamos viendo cómo queda con el Animator Controller
