### ISSUE TITLE
Creación de escenario

### ISSUE THREAD

**Issue by Guillermo-Manso** [CIFP-Jose-luis-Garci/ZeikkusAwakening#23]
- [x] Modelar terreno
- [x] Modelar objetos
- [x] Texturizar terreno
- [x] Texturizar objetos
- [x] Exportar

**Comment by alhgo** [comment]
Venga, ahora que ya tenemos los vídeos en EducaMadrid, ¿quién se lanza a crear un terreno en una escena nueva, que luego convertirá en prefab? 
Si queréis un tutorial sencillo de cómo crear escenarios de fantasía usando el URP (os hablaré de él en clase) tenéis este vídeo: [https://www.youtube.com/watch?v=Fhx7t0REfMI](https://www.youtube.com/watch?v=Fhx7t0REfMI)
