### ISSUE TITLE
Diagrama de Gantt

### ISSUE THREAD

**Issue by ZeikkuSSJ7** [CIFP-Jose-luis-Garci/ZeikkusAwakening#26]

**Comment by vcalzadaga** [comment]
Hola!

¿Podéis subir todos los documentos en un archivo zip? Tal y como están no consigo abrir los documentos

Gracias

**Comment by Guillermo-Manso** [comment]
[Diagrama Gant.zip](https://github.com/CIFP-Jose-luis-Garci/ZeikkusAwakening/files/7725417/Diagrama.Gant.zip)
