### ISSUE TITLE
Issue para comentarios

### ISSUE THREAD

**Issue by ZeikkuSSJ7** [CIFP-Jose-luis-Garci/ZeikkusAwakening#37]
Buenas equipo. Acabo de mandaros unas cuantas issues para que vayáis haciendo en Navidad. Lo más importante: no os preocupéis si algo parece difícil. Tengo en cuenta que necesitaréis ayuda o tendréis dudas sobre vuestra tarea, así que para cualquier cosa me decís y os ayudo. Por lo demás, si hay algo que encontráis para tutoriales, recursos o cualquier problema con Unity que hayáis solucionado, comentadlo por aquí y así todos nos enteramos. Yo mayormente usaré este issue para comentar cosas a todos en cuanto haga algún cambio importante como este

Cosas generales a tener en cuenta con el proyecto

1.  Estamos usando Universal Render Pipeline, que no es compatible con el normal. Por lo tanto, si algun asset os aparece morado, investigad que shader usa su material (cambiadlo a Universal Render Pipeline/Lit)
2.  Ya no usamos el sistema de Input de Unity estándar, he migrado el proyecto al InputSystem para que sea mucho más fácil de manejar. Cualquier pregunta, ya sabéis
3.  Siempre que hagáis algún efecto o shader, intentad que se produzca con ShaderGraph o VFX ShaderGraph para mantener consistencia
4.  No os agobiéis si no sale algo bien (preguntadme, sin problema respondo cuando sea), sobretodo ahora de vacaciones, pero pensad que este es el mejor momento para ponerse a trabajar

Por supuesto, si alguien piensa que hay que cambair algo, decidme y lo hablamos en clase o por WA
Buenas noches

**Comment by alhgo** [comment]
Solo un comentario: tras hablar con Jorge, he decidido incorporar el nuevo InputSystem a la siguiente práctica de clase, y también usaremos efectos basados en volumen del URP, así que lo que aprendáis ahora os servirá para clase (no solo para el GDD), y lo que no aprendáis, tendréis que hacerlo más adelante. 😁
