### ISSUE TITLE
Efectos de sonido y banda sonora

### ISSUE THREAD

**Issue by Guillermo-Manso** [CIFP-Jose-luis-Garci/ZeikkusAwakening#5]

**Comment by alejandroaguayo1** [comment]
[Sonido, música y efectos.docx](https://github.com/CIFP-Jose-luis-Garci/ZeikkusAwakening/files/7496906/Sonido.musica.y.efectos.docx)
Adjunto el documento correspondiente.

**Comment by vcalzadaga** [comment]
Falta añadir una muestra representativa de sonidos para el juego. No hace falta que sean los sonidos definitivos, pero sí que sean parecidos a los sonidos definitivos que tendrá el juego

**Comment by alejandroaguayo1** [comment]
[Sonidos.docx](https://github.com/CIFP-Jose-luis-Garci/ZeikkusAwakening/files/7519550/Sonidos.docx)
Adjunto el documento con los enlaces a efectos de sonido y música que se acercaría a la final.
