### ISSUE TITLE
Argumento y desarrollo

### ISSUE THREAD

**Issue by Guillermo-Manso** [CIFP-Jose-luis-Garci/ZeikkusAwakening#6]
- [x] Argumento
- [x] Desarrollo

**Comment by vcalzadaga** [comment]
No puedo abrir los documentos. Intentad subirlos de nuevo please

**Comment by Guillermo-Manso** [comment]
[Historia.pdf](https://github.com/CIFP-Jose-luis-Garci/ZeikkusAwakening/files/7518891/Historia.pdf)
Historia
