### ISSUE TITLE
Mercado objetivo y juegos exitosos

### ISSUE THREAD

**Issue by Guillermo-Manso** [CIFP-Jose-luis-Garci/ZeikkusAwakening#8]

**Comment by alejandroaguayo1** [comment]
[Análisis de mercado .docx](https://github.com/CIFP-Jose-luis-Garci/ZeikkusAwakening/files/7496910/Analisis.de.mercado.docx)
Adjunto el documento correspondiente.

**Comment by vcalzadaga** [comment]
Muy bien justificado

**Comment by vcalzadaga** [comment]
Ups, lo abrí sin querer. Lo cierro de nuevo
